# Generated by Django 4.0.5 on 2022-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_modified', models.DateTimeField(verbose_name='date modified')),
                ('date', models.DateField(verbose_name='date')),
                ('protein', models.CharField(max_length=50, verbose_name='protein')),
                ('starch', models.CharField(max_length=50, verbose_name='starch')),
                ('veggie', models.CharField(max_length=50, verbose_name='vegetable')),
                ('sauce', models.CharField(max_length=50, verbose_name='sauce')),
                ('extra', models.CharField(blank=True, max_length=50, null=True, verbose_name='extra')),
            ],
        ),
    ]
