# Generated by Django 4.0.5 on 2022-06-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discarded',
            field=models.BooleanField(default=False, verbose_name='discarded'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='ct',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='item count'),
        ),
    ]
